spring:
  security:
    user:
      name: user
      password: '{noop}password'
      roles:
        - SERVICE
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
  datasource:
    url: jdbc:postgresql://localhost:5432/catalog
    username: catalog
    password: catalog
  flyway:
    schemas:
      - public
      - catalog
  jpa:
    show-sql: true
server:
  port: 8081
logging:
  level:
    sql: info
