selmag:
  services:
    catalog:
      uri: http://localhost:8081
      username: user
      password: password
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager